# -*- coding: utf-8 -*-
"""
KACHINOVA — film pass
=====================
Takes the six delivered clips and makes them part of the same production as
the stills:

  1. Exports the exact grade used by tools/media.py as a 3D LUT (.cube), so
     motion and stills are colour-identical by construction rather than by eye.
  2. Crops to a true 16:9, upscales, applies the LUT, vignette and grain.
  3. Rebuilds each clip as a SEAMLESS LOOP by dissolving its tail into its
     head — the delivered clips are one-way camera moves and would otherwise
     jump-cut every time they repeat.
  4. Re-exports every poster from the finished film, so the still the visitor
     sees before playback is the same frame the video starts on.

Run:  python tools/films.py            # all six
      python tools/films.py city ai    # only the named shots
"""
from __future__ import annotations

import os
import subprocess
import sys

import numpy as np
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from media import (LUT, _scurve, export, OUT_IMG, OUT_POSTER, OUT_MASTER,  # noqa: E402
                   vignette, THEME, RESIDUAL_SAT)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = r"C:\Users\kenta\Downloads"
CUBE = os.path.join(ROOT, "tools", f"kachinova-{THEME}.cube")
CUBE_REL = f"tools/kachinova-{THEME}.cube"
OUT_VID = os.path.join(ROOT, "assets", "videos")
WORK = os.path.join(ROOT, ".media-masters")

os.makedirs(OUT_VID, exist_ok=True)
os.makedirs(WORK, exist_ok=True)

# shot -> (delivered filename stem, poster frame as a fraction of the clip)
FILMS = {
    "city":    ("Create a premium cinematic background film for a J", 0.30),
    "ai":      ("Create a sophisticated cinematic visualization of",  0.42),
    "revalue": ("Create a cinematic transformation film representin", 0.78),
    "smart":   ("Create an intimate cinematic film showing invisibl", 0.55),
    "eco":     ("Create an emotional cinematic architectural film a", 0.72),
    "future":  ("Create a powerful but understated closing cinemati", 0.34),
}

# Editorial stills lifted from the films, so the whole site is one production.
# shot -> [(still name, fraction)]
STILLS_FROM_FILM = {
    "city":    [("about-city", 0.62)],
    "ai":      [("tech-mind", 0.13)],   # a different moment than the poster (42%)
    "revalue": [("why-reuse", 0.06)],   # the bare, unrenovated home = existing stock
    "future":  [("sell-city", 0.88)],
}

SRC_W, SRC_H = 864, 496
CROP_H = 486                 # 864x486 = exact 16:9
OUT_W, OUT_H = 1280, 720
FPS = 24
CLIP = 15.0                  # usable source seconds
BLEND = 1.6                  # tail-into-head dissolve
MID_END = CLIP - BLEND       # 13.4


# ------------------------------------------------------------------- LUT ----
def write_cube(size: int = 33) -> None:
    """Bake tools/media.py's grade() into a 3D LUT.

    Must stay in lockstep with grade(): same S-curve, same tritone ramp, same
    residual chroma. Grain is deliberately excluded — ffmpeg adds it per frame,
    otherwise the same noise pattern would be frozen onto every frame."""
    g = np.linspace(0.0, 1.0, size)
    b, gg, r = np.meshgrid(g, g, g, indexing="ij")      # cube order: R fastest
    rgb = np.stack([r, gg, b], axis=-1).reshape(-1, 3)

    lum = rgb[:, 0] * 0.2126 + rgb[:, 1] * 0.7152 + rgb[:, 2] * 0.0722
    lum = _scurve(lum)
    idx = np.clip((lum * 255.0).round().astype(np.int32), 0, 255)
    toned = LUT[idx] / 255.0
    chroma = rgb - lum[:, None]
    out = np.clip(toned + chroma * 0.13, 0.0, 1.0)

    with open(CUBE, "w", encoding="ascii") as f:
        f.write("# KACHINOVA film grade - generated by tools/films.py\n")
        f.write("# Mirrors grade() in tools/media.py (minus per-frame grain).\n")
        f.write(f"LUT_3D_SIZE {size}\n")
        f.write("DOMAIN_MIN 0.0 0.0 0.0\nDOMAIN_MAX 1.0 1.0 1.0\n")
        for v in out:
            f.write(f"{v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
    print(f"  LUT written: {os.path.relpath(CUBE, ROOT)} ({size}^3)  theme={THEME}")


# Post-grade mean luminance each film should land on. This is the light arc of
# the scroll: dawn -> dark interior -> transformation -> dusk -> morning ->
# night. Matching every clip to one number would flatten the story; these keep
# the intent while removing the accidental 3.3x exposure spread between the
# delivered files.
TARGET_L = {
    # DARK — the light arc of the scroll at night.
    "dark": {
        "city": 0.24, "ai": 0.22, "revalue": 0.38,
        "smart": 0.30, "eco": 0.46, "future": 0.18,
    },
    # LIGHT — the same arc, played high-key. Kept as a spread rather than one
    # flat value: without it the six clips become interchangeable white boxes
    # and the scroll loses its sense of time passing.
    "light": {
        "city": 0.58, "ai": 0.60, "revalue": 0.70,
        "smart": 0.62, "eco": 0.78, "future": 0.50,
    },
}[THEME]

_VIGNETTE_MEAN = 0.97 if THEME == "light" else 0.93   # vignette is lighter on white


def _grade_np(rgb: np.ndarray) -> np.ndarray:
    """Same maths as media.grade(), minus grain — used to solve for exposure."""
    lum = rgb @ np.array([0.2126, 0.7152, 0.0722])
    lum = _scurve(lum)
    idx = np.clip((lum * 255.0).round().astype(np.int32), 0, 255)
    toned = LUT[idx] / 255.0
    return np.clip(toned + (rgb - lum[:, None]) * RESIDUAL_SAT, 0.0, 1.0)


def probe_frames(shot: str, n: int = 6) -> np.ndarray:
    """Sample the delivered clip so exposure can be measured, not guessed."""
    stem, _ = FILMS[shot]
    d = os.path.join(WORK, "_probe")
    os.makedirs(d, exist_ok=True)
    pat = os.path.join(d, f"{shot}_%03d.png")
    run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
         "-i", os.path.join(SRC, stem + ".mp4"),
         "-vf", f"crop={SRC_W}:{CROP_H},fps=1/2.4,scale=320:-1",
         "-frames:v", str(n), pat])
    out = []
    for i in range(1, n + 1):
        f = os.path.join(d, f"{shot}_{i:03d}.png")
        if os.path.exists(f):
            out.append(np.asarray(Image.open(f).convert("RGB"), dtype=np.float64) / 255.0)
    return np.concatenate([x.reshape(-1, 3) for x in out])


def solve_gamma(shot: str) -> float:
    """Binary-search the pre-LUT gamma that puts this clip on its target.
    ffmpeg's eq filter computes pow(x, 1/gamma), so >1 brightens."""
    px = probe_frames(shot)
    target = TARGET_L[shot]

    def mean_at(g: float) -> float:
        pre = np.power(px, 1.0 / g)
        out = _grade_np(pre)
        return float((out @ np.array([0.2126, 0.7152, 0.0722])).mean()) * _VIGNETTE_MEAN

    lo, hi = 0.35, 4.0
    for _ in range(40):
        mid = (lo + hi) / 2
        if mean_at(mid) < target:
            lo = mid
        else:
            hi = mid
    g = round((lo + hi) / 2, 3)
    print(f"  {shot:9s} exposure gamma {g:5.3f}  -> mean L {mean_at(g):.3f} (target {target:.2f})")
    return g


# ------------------------------------------------------------------ video ---
def grade_chain(gamma: float) -> str:
    return (
        f"crop={SRC_W}:{CROP_H},"
        f"scale={OUT_W}:{OUT_H}:flags=lanczos,"
        "format=rgb24,"
        f"eq=gamma={gamma}:eval=init,"
        f"lut3d=file={CUBE_REL}:interp=tetrahedral,"
        "unsharp=5:5:0.34:5:5:0,"
        + ("vignette=PI/9," if THEME == "light" else "vignette=PI/5,")
        + ("noise=alls=3:allf=t," if THEME == "light" else "noise=alls=5:allf=t,")
        +
        "format=yuv420p,"
        f"fps={FPS},setpts=PTS-STARTPTS"
    )


def loop_filter(gamma: float) -> str:
    """mid + dissolve(tail -> head): the last frame of the dissolve matches the
    first frame of mid, so the clip repeats without a cut."""
    return (
        f"[0:v]{grade_chain(gamma)}[g];"
        "[g]split=3[g1][g2][g3];"
        f"[g1]trim=0:{BLEND},setpts=PTS-STARTPTS[head];"
        f"[g2]trim={BLEND}:{MID_END},setpts=PTS-STARTPTS[mid];"
        f"[g3]trim={MID_END}:{CLIP},setpts=PTS-STARTPTS[tail];"
        f"[tail][head]xfade=transition=fade:duration={BLEND}:offset=0[blend];"
        "[mid][blend]concat=n=2:v=1[out]"
    )


def run(cmd: list[str]) -> None:
    p = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, encoding="utf-8", errors="replace")
    if p.returncode != 0:
        print(p.stderr[-2500:])
        raise SystemExit(f"ffmpeg failed: {' '.join(cmd[:6])} …")


def build(shot: str) -> None:
    stem, _frac = FILMS[shot]
    src = os.path.join(SRC, stem + ".mp4")
    if not os.path.isfile(src):
        print(f"  !! missing source for {shot}: {src}")
        return

    mp4 = os.path.join(OUT_VID, f"kachinova-{shot}.mp4")
    webm = os.path.join(OUT_VID, f"kachinova-{shot}.webm")
    fc = loop_filter(solve_gamma(shot))

    print(f"  {shot}.mp4")
    run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", src,
         "-filter_complex", fc, "-map", "[out]", "-an",
         "-c:v", "libx264", "-profile:v", "high", "-level", "4.0",
         "-pix_fmt", "yuv420p", "-crf", "28", "-preset", "slow",
         "-g", str(FPS * 2), "-movflags", "+faststart", mp4])

    # CRF 44 rather than 38: these are background plates sitting under a heavy
    # scrim, and A/B at CRF 38 vs 46 measured 39.5 dB PSNR — the extra bits buy
    # grain nobody can see through the gradient. 1.32 MB -> ~0.6 MB per clip.
    print(f"  {shot}.webm")
    run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", src,
         "-filter_complex", fc, "-map", "[out]", "-an",
         "-c:v", "libvpx-vp9", "-pix_fmt", "yuv420p", "-b:v", "0", "-crf", "44",
         "-row-mt", "1", "-deadline", "good", "-cpu-used", "3", webm])


def frame_at(shot: str, frac: float, dest_png: str) -> None:
    """Pull one already-graded frame out of the finished film."""
    mp4 = os.path.join(OUT_VID, f"kachinova-{shot}.mp4")
    t = max(0.0, (MID_END - BLEND) * frac)
    run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
         "-ss", f"{t:.2f}", "-i", mp4, "-frames:v", "1",
         "-vf", "scale=1920:1080:flags=lanczos", dest_png])


def posters(shot: str) -> None:
    _stem, frac = FILMS[shot]
    master = os.path.join(OUT_MASTER, f"{shot}.png")
    frame_at(shot, frac, master)
    export(Image.open(master).convert("RGB"),
           os.path.join(OUT_POSTER, f"kachinova-{shot}"))
    print(f"  poster {shot} @ {frac:.0%}")

    for name, f in STILLS_FROM_FILM.get(shot, []):
        tmp = os.path.join(OUT_MASTER, f"_still-{name}.png")
        frame_at(shot, f, tmp)
        im = Image.open(tmp).convert("RGB")
        im = im.resize((1600, 900), Image.LANCZOS)
        im.save(os.path.join(OUT_IMG, f"{name}.webp"), "WEBP", quality=74, method=6)
        im.save(os.path.join(OUT_IMG, f"{name}.jpg"), "JPEG", quality=76,
                optimize=True, progressive=True)
        print(f"  still  {name} <- {shot} @ {f:.0%}")


if __name__ == "__main__":
    want = [a for a in sys.argv[1:] if not a.startswith("-")]
    shots = want or list(FILMS)
    print(f"KACHINOVA film pass  theme={THEME}")
    write_cube()
    for s in shots:
        if s not in FILMS:
            print(f"  ?? unknown shot {s}")
            continue
        build(s)
        posters(s)
    print("done.")
